# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yUEkOQzKEZst6gxcaVTCqNfG_8yh8YiO
"""

#23.1
import folium
m = folium.Map(location=[10.7610783, 106.6685175],zoom_start=12)
folium.Marker(
    location=(10.761462371060425, 106.66834115955066),
    popup="UEH",
    icon=folium.Icon( color="red"),
    tooltip="UEH"
).add_to(m)
folium.Marker(
    location=(10.76289582784658, 106.67010068862302),
    popup="TT Y Khoa Hoa Hao",
    icon=folium.Icon(color="blue"),
    tooltip="TT Y Khoa Hoa Hao"
).add_to(m)
folium.Marker(
    location=(10.761042369414433, 106.6726950596748),
    popup="Chua Giac Ngo",
    icon=folium.Icon(color="pink"),
    tooltip="Chua Giac Ngo"
).add_to(m)
folium.Marker(
    location=(10.760640238402717, 106.66434121721159),
    popup="Dao Duy Tu",
    icon=folium.Icon(color="lightgray"),
    tooltip="Dao Duy Tu"
).add_to(m)
folium.Marker(
    location=(10.758911644381243, 106.67206597899269),
    popup="Cho An Dong",
    icon=folium.Icon(color="cadetblue"),
    tooltip="Cho An Dong"
).add_to(m)
m.save("map.html")
m

#23.2
from geopy.geocoders import Nominatim
from geopy.distance import geodesic
import folium

geolocator = Nominatim(user_agent="ai_homework")

# Danh sách 10 địa chỉ
addresses = [
    "Đại học Kinh tế TP.HCM",
    "Bệnh viện Chợ Rẫy, TP.HCM",
    "Chợ Bến Thành, TP.HCM",
    "Nhà thờ Đức Bà, TP.HCM",
    "Dinh Độc Lập, TP.HCM",
    "Bến xe Miền Đông mới",
    "Sân bay Tân Sơn Nhất",
    "Đại học Bách Khoa TP.HCM",
    "Bưu điện Trung tâm Sài Gòn",
    "Bitexco Financial Tower"
]
center = geolocator.geocode("Đại học Kinh tế TP.HCM")
center_coords = (center.latitude, center.longitude)
results = []
for addr in addresses:
    loc = geolocator.geocode(addr)
    if loc:
        coords = (loc.latitude, loc.longitude)
        dist = geodesic(center_coords, coords).km
        results.append({"address": addr, "lat": loc.latitude,
                       "lon": loc.longitude, "distance_km": dist})
    import time; time.sleep(1)  # Tránh rate limit

# Vẽ trên Folium
m = folium.Map(location=list(center_coords), zoom_start=13)
for r in results:
    folium.Marker(
        [r['lat'], r['lon']],
        popup=f"{r['address']}<br>Cách trung tâm: {r['distance_km']:.2f} km"
    ).add_to(m)
    folium.PolyLine(
        [center_coords, (r['lat'], r['lon'])],
        color='blue', weight=1, opacity=0.5
    ).add_to(m)
m

#23.3
import folium
from folium.plugins import HeatMap
import numpy as np
np.random.seed(42)
center_lat, center_lon = 10.7769, 106.7009
data = []
clusters = [(10.78, 106.70, 80), (10.73, 106.72, 60), (10.85, 106.75, 60)]
for clat, clon, n in clusters:
    lats = np.random.normal(clat, 0.008, n)
    lons = np.random.normal(clon, 0.008, n)
    data.extend([[lat, lon] for lat, lon in zip(lats, lons)])
m = folium.Map(location=[center_lat, center_lon], zoom_start=13)
HeatMap(data, radius=15, blur=10, max_zoom=17).add_to(m)
m.save("bai_23_3_heatmap.html")
m

#23.4
import geopandas as gpd
import folium
import pandas as pd
geo_data = gpd.read_file("vietnam_provinces.geojson")
revenue_data = pd.DataFrame({
    'province': geo_data['name'].tolist(),
    'revenue': np.random.randint(100, 1000, len(geo_data))
})

geo_merged = geo_data.merge(revenue_data, left_on='name', right_on='province')

m = folium.Map(location=[16.0, 106.0], zoom_start=6)
folium.Choropleth(
    geo_data=geo_merged,
    data=revenue_data,
    columns=['province', 'revenue'],
    key_on='feature.properties.name',
    fill_color='YlOrRd',
    legend_name='Doanh thu (tỷ VNĐ)'
).add_to(m)
m.save("index.html")
m

#23.5
import folium
warehouse = [10.7769, 106.7009]
m = folium.Map(location=warehouse, zoom_start=13)

folium.Marker(warehouse, popup="Kho trung tâm",
              icon=folium.Icon(color='red', icon='home')).add_to(m)
for radius, color in [(3000, 'green'), (5000, 'orange'), (10000, 'red')]:
    folium.Circle(
        location=warehouse, radius=radius,
        color=color, fill=True, fill_opacity=0.1,
        popup=f"Bán kính {radius//1000} km"
    ).add_to(m)
m

#23.6
import osmnx as ox
import networkx as nx
import folium
import webbrowser, os

# Cấu hình
ox.settings.log_console = True
ox.settings.use_cache = True

# 1. Tải dữ liệu
print("Đang tải dữ liệu mạng đường...")
G = ox.graph_from_place("Quận 1, Hồ Chí Minh, Vietnam", network_type="drive")
print("Tải xong")

# 2. Thống kê
stats = ox.basic_stats(G)
nodes, edges = ox.graph_to_gdfs(G)

intersection_density = stats.get('intersection_density_km', 0)
street_length_avg = stats.get('street_length_avg', 0)

print(f"""
==================================================
THỐNG KÊ MẠNG GIAO THÔNG QUẬN 1
==================================================
Số nút giao:              {stats['n']}
Số đoạn đường:            {stats['m']}
Chiều dài trung bình:     {street_length_avg:.1f} m
Tổng chiều dài:           {stats['street_length_total']/1000:.1f} km
Mật độ giao lộ:           {intersection_density:.1f} giao lộ/km²
Số đường trung bình/nút:  {stats['streets_per_node_avg']:.2f}
""")

# 3. Vẽ ảnh tĩnh
fig, ax = ox.plot_graph(
    G, figsize=(10,10),
    node_size=5,
    edge_color="#333",
    edge_linewidth=0.5,
    bgcolor="white",
    show=False, close=True
)

fig.savefig("network_q1.png", dpi=150, bbox_inches="tight")

# 4. Bản đồ tương tác
m = folium.Map(location=[10.775, 106.700], zoom_start=15)

for _, edge in edges.iterrows():
    if edge.geometry is None:
        continue

    coords = [(pt[1], pt[0]) for pt in edge.geometry.coords]

    name = edge.get("name", "Không tên")
    if isinstance(name, list):
        name = ", ".join(name)

    length = edge.get("length", 0)

    folium.PolyLine(
        coords,
        color="#2c3e50",
        weight=2,
        opacity=0.7,
        tooltip=f"{name} — {length:.0f}m"
    ).add_to(m)

for node_id, data in G.nodes(data=True):
    if G.degree(node_id) >= 4:
        folium.CircleMarker(
            [data["y"], data["x"]],
            radius=3,
            color="red",
            fill=True
        ).add_to(m)

m.save("map_q1.html")
webbrowser.open("file://" + os.path.abspath("map_q1.html"))

print("Đã tạo xong bản đồ")
m

pip insall osmnx

pip install osmnx

pip install networkx

#23.7
import osmnx as ox
import networkx as nx
import time

G = ox.graph_from_place("Quận 1, Hồ Chí Minh, Vietnam",
                         network_type='drive')

orig = ox.nearest_nodes(G, 106.695, 10.780)  # X=lon, Y=lat
dest = ox.nearest_nodes(G, 106.705, 10.770)

t1 = time.time()
route_dij = nx.shortest_path(G, orig, dest, weight='length',
                              method='dijkstra')
t_dij = time.time() - t1
def heuristic(u, v):
    from geopy.distance import geodesic
    u_data = G.nodes[u]
    v_data = G.nodes[v]
    return geodesic((u_data['y'], u_data['x']),
                    (v_data['y'], v_data['x'])).m
t2 = time.time()
route_astar = nx.astar_path(G, orig, dest, heuristic=heuristic,
                             weight='length')
t_astar = time.time() - t2

print(f"Dijkstra: {len(route_dij)} nodes, {t_dij:.4f}s")
print(f"A*:       {len(route_astar)} nodes, {t_astar:.4f}s")

fig, ax = ox.plot_graph_routes(G, [route_dij, route_astar],
                                route_colors=['blue', 'red'])
m

#23.8
from scipy.optimize import linear_sum_assignment
from geopy.distance import geodesic
import numpy as np, folium

np.random.seed(42)
customers = np.random.normal([10.78, 106.70], 0.01, (5, 2))
drivers = np.random.normal([10.78, 106.70], 0.015, (5, 2))

cost = np.array([[geodesic(c, d).km for d in drivers] for c in customers])

row_ind, col_ind = linear_sum_assignment(cost)

m = folium.Map(location=[10.78, 106.70], zoom_start=14)
colors = ['red','blue','green','purple','orange']
for i, j in zip(row_ind, col_ind):
    folium.Marker(customers[i].tolist(), popup=f"Khách {i}",
                  icon=folium.Icon(color=colors[i])).add_to(m)
    folium.Marker(drivers[j].tolist(), popup=f"Xe {j}",
                  icon=folium.Icon(color=colors[i], icon='car',
                                   prefix='fa')).add_to(m)
    folium.PolyLine([customers[i].tolist(), drivers[j].tolist()],
                     color=colors[i]).add_to(m)
m.save("index3.html")
m

#23.9
from sklearn.cluster import KMeans
import numpy as np, folium

np.random.seed(42)
data = np.vstack([
    np.random.normal([10.78, 106.70], 0.005, (40, 2)),
    np.random.normal([10.75, 106.72], 0.005, (30, 2)),
    np.random.normal([10.82, 106.68], 0.005, (30, 2)),
])


kmeans = KMeans(n_clusters=3, random_state=42).fit(data)
labels = kmeans.labels_
centers = kmeans.cluster_centers_


m = folium.Map(location=[10.78, 106.70], zoom_start=13)
colors = ['red', 'blue', 'green']
for point, label in zip(data, labels):
    folium.CircleMarker(point.tolist(), radius=3,
                        color=colors[label], fill=True).add_to(m)
for i, c in enumerate(centers):
    folium.Marker(c.tolist(), popup=f"ĐỀ XUẤT: Kho {i+1}",
                  icon=folium.Icon(color=colors[i], icon='star')).add_to(m)
m.save("index4.html")
m

#23.10
import numpy as np
import folium
from folium.plugins import HeatMap
import webbrowser, os

# 1. Dữ liệu giả lập: 12 tuyến đường ở TP.HCM
np.random.seed(42)
roads = [
    {"name": "Nguyễn Huệ",        "lat": 10.7736, "lon": 106.7031, "lanes": 4, "density": 90, "peak": True},
    {"name": "Lê Lợi",            "lat": 10.7725, "lon": 106.6980, "lanes": 4, "density": 85, "peak": True},
    {"name": "Điện Biên Phủ",     "lat": 10.7870, "lon": 106.6960, "lanes": 6, "density": 80, "peak": True},
    {"name": "Cách Mạng Tháng 8", "lat": 10.7860, "lon": 106.6850, "lanes": 6, "density": 75, "peak": True},
    {"name": "Nguyễn Thị Minh Khai","lat":10.7810, "lon": 106.6920, "lanes": 4, "density": 88, "peak": True},
    {"name": "Võ Văn Tần",        "lat": 10.7780, "lon": 106.6880, "lanes": 3, "density": 70, "peak": False},
    {"name": "Nam Kỳ Khởi Nghĩa", "lat": 10.7830, "lon": 106.6930, "lanes": 4, "density": 65, "peak": False},
    {"name": "Pasteur",           "lat": 10.7850, "lon": 106.6970, "lanes": 3, "density": 45, "peak": False},
    {"name": "Hai Bà Trưng",      "lat": 10.7880, "lon": 106.7000, "lanes": 4, "density": 55, "peak": False},
    {"name": "Trần Hưng Đạo",     "lat": 10.7650, "lon": 106.6920, "lanes": 6, "density": 72, "peak": True},
    {"name": "Nguyễn Trãi (Q5)",  "lat": 10.7560, "lon": 106.6700, "lanes": 6, "density": 82, "peak": True},
    {"name": "Lý Thường Kiệt",    "lat": 10.7750, "lon": 106.6600, "lanes": 4, "density": 40, "peak": False},
]

# 2. Hàm Fuzzy Logic tính nguy cơ tắc nghẽn
def fuzzy_congestion(density, is_peak, num_lanes):
    """
    3 biến đầu vào mờ → 1 đầu ra: nguy cơ tắc nghẽn [0, 1]
    - mu_density: mật độ xe (0-100) → càng cao càng rủi ro
    - mu_peak: giờ cao điểm → rủi ro cao hơn
    - mu_lanes: ít làn → rủi ro cao hơn
    """
    mu_density = min(density / 100, 1.0)
    mu_peak = 1.0 if is_peak else 0.3
    mu_lanes = max(0, 1 - num_lanes / 8)

    # Luật mờ (Fuzzy Rules) — Max-Min inference
    r1 = min(mu_density, mu_peak)       # Đông + giờ cao điểm → tắc
    r2 = min(mu_density, mu_lanes)      # Đông + ít làn → tắc
    r3 = min(mu_peak, mu_lanes)         # Cao điểm + ít làn → tắc
    r4 = mu_density * 0.5              # Đông đơn thuần

    risk = max(r1, r2, r3, r4)  # Defuzzification: lấy max
    return round(risk, 3)

# 3. Tính nguy cơ cho từng tuyến
for r in roads:
    r["risk"] = fuzzy_congestion(r["density"], r["peak"], r["lanes"])
    r["level"] = "CAO" if r["risk"] >= 0.7 else ("TRUNG BÌNH" if r["risk"] >= 0.4 else "THẤP")

# 4. Vẽ bản đồ
m = folium.Map(location=[10.775, 106.690], zoom_start=15, tiles="CartoDB positron")

# Heatmap nguy cơ
heat_data = []
for r in roads:
    for _ in range(int(r["risk"] * 30)):
        heat_data.append([r["lat"] + np.random.normal(0, 0.001),
                          r["lon"] + np.random.normal(0, 0.001), r["risk"]])
HeatMap(heat_data, radius=20, blur=15, max_zoom=17).add_to(m)

# Markers từng tuyến
color_map = {"CAO": "red", "TRUNG BÌNH": "orange", "THẤP": "green"}
for r in roads:
    folium.CircleMarker(
        [r["lat"], r["lon"]], radius=10 + r["risk"] * 15,
        color=color_map[r["level"]], fill=True, fill_opacity=0.7,
        tooltip=f"{r['name']}: {r['level']} ({r['risk']:.0%})",
        popup=f"<b>{r['name']}</b><br>Mật độ: {r['density']}%<br>"
              f"Số làn: {r['lanes']}<br>Giờ cao điểm: {'Có' if r['peak'] else 'Không'}<br>"
              f"<b style='color:{color_map[r['level']]}'>Nguy cơ: {r['risk']:.0%} ({r['level']})</b>"
    ).add_to(m)

# 5. Đề xuất tuyến thay thế (nối các điểm rủi ro THẤP)
safe = [r for r in roads if r["level"] == "THẤP"]
if len(safe) >= 2:
    route = [[r["lat"], r["lon"]] for r in safe]
    folium.PolyLine(route, color="green", weight=5, opacity=0.8,
                    dash_array="10", tooltip="TUYẾN THAY THẾ ĐỀ XUẤT").add_to(m)

# Nối các điểm rủi ro CAO để cảnh báo
danger = [r for r in roads if r["level"] == "CAO"]
if len(danger) >= 2:
    route_d = [[r["lat"], r["lon"]] for r in danger]
    folium.PolyLine(route_d, color="red", weight=4, opacity=0.6,
                    dash_array="5", tooltip="⚠️ VÙNG TẮC NGHẼN").add_to(m)

# Chú thích
legend = """
<div style="position:fixed;bottom:30px;left:30px;z-index:9999;background:white;
     padding:12px;border-radius:8px;box-shadow:0 2px 6px rgba(0,0,0,0.3);font-size:12px">
    <b>Bài 23.10 — Nguy cơ tắc nghẽn (Fuzzy Logic)</b><br>
    🔴 Cao (≥70%) &nbsp; 🟠 Trung bình (40-70%) &nbsp; 🟢 Thấp (<40%)<br>
    <span style="color:green">- - - Tuyến thay thế đề xuất</span> &nbsp;
    <span style="color:red">- - - Vùng tắc nghẽn</span>
</div>"""
m.get_root().html.add_child(folium.Element(legend))
m.save("bai_23_10.html")
webbrowser.open('file://' + os.path.realpath("bai_23_10.html"))

# 6. In kết quả
print("=== KẾT QUẢ PHÂN TÍCH TẮC NGHẼN ===")
for r in sorted(roads, key=lambda x: -x["risk"]):
    print(f"  {r['name']:25s} | Nguy cơ: {r['risk']:.0%} | {r['level']}")
print(f"\nVùng nguy hiểm: {', '.join(r['name'] for r in danger)}")
print(f"Tuyến thay thế : {' → '.join(r['name'] for r in safe)}")
m

# Commented out IPython magic to ensure Python compatibility.
#23.11
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, r2_score
import folium
from folium.plugins import HeatMap
import webbrowser
import os

# ==============================================================
# 1. TẠO DỮ LIỆU GIẢ LẬP
# ==============================================================
np.random.seed(42)

# Định nghĩa 8 khu vực ở TP.HCM
regions = {
    0: {"name": "Quận 1",     "lat": 10.7756, "lon": 106.7019, "base_demand": 50},
    1: {"name": "Quận 3",     "lat": 10.7834, "lon": 106.6868, "base_demand": 40},
    2: {"name": "Quận 7",     "lat": 10.7340, "lon": 106.7215, "base_demand": 35},
    3: {"name": "Bình Thạnh", "lat": 10.8056, "lon": 106.7094, "base_demand": 38},
    4: {"name": "Thủ Đức",    "lat": 10.8494, "lon": 106.7537, "base_demand": 30},
    5: {"name": "Tân Bình",   "lat": 10.8018, "lon": 106.6528, "base_demand": 33},
    6: {"name": "Gò Vấp",     "lat": 10.8386, "lon": 106.6652, "base_demand": 28},
    7: {"name": "Phú Nhuận",  "lat": 10.7990, "lon": 106.6802, "base_demand": 32},
}

data_rows = []

for day in range(1, 31):          # 30 ngày
    day_of_week = day % 7         # 0-6 (0=CN, 6=T7)
    is_weekend = 1 if day_of_week in [0, 6] else 0

    for hour in range(6, 24):     # 6h sáng đến 23h
        for region_id, info in regions.items():

            # Mô phỏng nhu cầu thực tế
            base = info["base_demand"]

            # Hiệu ứng giờ cao điểm (7-9h sáng, 17-19h chiều)
            if hour in [7, 8, 9]:
                hour_factor = 1.8
            elif hour in [17, 18, 19]:
                hour_factor = 2.0
            elif hour in [11, 12, 13]:
                hour_factor = 1.3
            elif hour >= 22:
                hour_factor = 0.5
            else:
                hour_factor = 1.0

            # Cuối tuần: nhu cầu giải trí tăng ở Q1, Q7
            if is_weekend:
                if region_id in [0, 2]:
                    weekend_factor = 1.4
                else:
                    weekend_factor = 0.85
            else:
                weekend_factor = 1.0

            # Tính nhu cầu + nhiễu ngẫu nhiên
            demand = base * hour_factor * weekend_factor
            demand += np.random.normal(0, demand * 0.15)  # nhiễu 15%
            demand = max(0, int(round(demand)))

            data_rows.append({
                "day": day,
                "day_of_week": day_of_week,
                "is_weekend": is_weekend,
                "hour": hour,
                "region_id": region_id,
                "region_name": info["name"],
                "lat": info["lat"],
                "lon": info["lon"],
                "demand": demand
            })

df = pd.DataFrame(data_rows)
print(f"Tổng số mẫu dữ liệu: {len(df)}")
print(f"\nThống kê nhu cầu:")
print(df.groupby("region_name")["demand"].describe().round(1))

# ==============================================================
# 2. HUẤN LUYỆN MÔ HÌNH RANDOM FOREST
# ==============================================================
# Features: khu vực, giờ, ngày trong tuần, cuối tuần
features = ["region_id", "hour", "day_of_week", "is_weekend"]
target = "demand"

X = df[features]
y = df[target]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Huấn luyện Random Forest
model = RandomForestRegressor(
    n_estimators=100,
    max_depth=10,
    random_state=42,
    n_jobs=-1
)
model.fit(X_train, y_train)

# Đánh giá
y_pred = model.predict(X_test)
mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"\n{'='*50}")
print(f"KẾT QUẢ MÔ HÌNH RANDOM FOREST")
print(f"{'='*50}")
print(f"MAE (Sai số trung bình):  {mae:.2f} lượt")
print(f"R² Score:                  {r2:.4f}")

# Độ quan trọng của features
importance = pd.Series(
    model.feature_importances_,
    index=features
).sort_values(ascending=False)
print(f"\nĐộ quan trọng các đặc trưng:")
for feat, imp in importance.items():
    print(f"  {feat:15s}: {imp:.4f} ({imp*100:.1f}%)")

# ==============================================================
# 3. DỰ ĐOÁN VÀ TRỰC QUAN HÓA TRÊN BẢN ĐỒ
# ==============================================================

# --- BẢN ĐỒ 1: Dự đoán nhu cầu giờ cao điểm chiều (18h, ngày thường) ---
m1 = folium.Map(location=[10.79, 106.70], zoom_start=13,
                tiles='CartoDB positron')

folium.TileLayer('OpenStreetMap').add_to(m1)

# Dự đoán cho từng khu vực lúc 18h ngày thường
pred_data_weekday = []
for region_id, info in regions.items():
    pred_input = pd.DataFrame([{
        "region_id": region_id,
        "hour": 18,
        "day_of_week": 3,     # Thứ 4
        "is_weekend": 0
    }])
    predicted = model.predict(pred_input)[0]
    pred_data_weekday.append({
        "name": info["name"],
        "lat": info["lat"],
        "lon": info["lon"],
        "demand": predicted
    })

# Tìm min/max để scale màu
demands = [d["demand"] for d in pred_data_weekday]
max_demand = max(demands)
min_demand = min(demands)

# Vẽ CircleMarker với kích thước và màu theo nhu cầu
for d in pred_data_weekday:
    # Scale bán kính từ 15 đến 40
    ratio = (d["demand"] - min_demand) / (max_demand - min_demand + 1e-9)
    radius = 15 + ratio * 25

    # Màu: xanh (thấp) → vàng → đỏ (cao)
    if ratio < 0.33:
        color = "green"
    elif ratio < 0.66:
        color = "orange"
    else:
        color = "red"

    folium.CircleMarker(
        location=[d["lat"], d["lon"]],
        radius=radius,
        color=color,
        fill=True,
        fill_color=color,
        fill_opacity=0.6,
        popup=folium.Popup(
            f"<b>{d['name']}</b><br>"
            f"Nhu cầu dự đoán (18h, ngày thường):<br>"
            f"<b style='font-size:16px; color:{color}'>{d['demand']:.0f} lượt</b>",
            max_width=250
        ),
        tooltip=f"{d['name']}: {d['demand']:.0f} lượt"
    ).add_to(m1)

# Tiêu đề bản đồ
title_html = """
<div style="position:fixed; top:10px; left:50%; transform:translateX(-50%);
     z-index:9999; background:white; padding:10px 20px; border-radius:8px;
     box-shadow:0 2px 6px rgba(0,0,0,0.3); font-family:Arial">
    <h3 style="margin:0; color:#333">Dự đoán nhu cầu gọi xe — 18h Ngày thường</h3>
    <p style="margin:4px 0 0; color:#666; font-size:12px">
        🟢 Thấp &nbsp; 🟠 Trung bình &nbsp; 🔴 Cao
        &nbsp;|&nbsp; Kích thước vòng tròn ~ mức nhu cầu
    </p>
</div>
"""
m1.get_root().html.add_child(folium.Element(title_html))

m1.save("bai_23_11_map1_weekday.html")
print("\n✅ Đã lưu bản đồ 1: bai_23_11_map1_weekday.html")

# --- BẢN ĐỒ 2: So sánh ngày thường vs cuối tuần (Heatmap) ---
m2 = folium.Map(location=[10.79, 106.70], zoom_start=13,
                tiles='CartoDB positron')

# Tạo 2 FeatureGroup: ngày thường vs cuối tuần
fg_weekday = folium.FeatureGroup(name="🟦 Ngày thường (18h)")
fg_weekend = folium.FeatureGroup(name="🟥 Cuối tuần (18h)")

for region_id, info in regions.items():
    # Dự đoán ngày thường
    pred_wd = model.predict(pd.DataFrame([{
        "region_id": region_id, "hour": 18,
        "day_of_week": 3, "is_weekend": 0
    }]))[0]

    # Dự đoán cuối tuần
    pred_we = model.predict(pd.DataFrame([{
        "region_id": region_id, "hour": 18,
        "day_of_week": 6, "is_weekend": 1
    }]))[0]

    # Chênh lệch
    diff = pred_we - pred_wd
    diff_pct = (diff / pred_wd) * 100 if pred_wd > 0 else 0
    arrow = "↑" if diff > 0 else "↓"

    # Marker ngày thường
    folium.CircleMarker(
        [info["lat"] - 0.002, info["lon"] - 0.002],
        radius=max(8, pred_wd / 4),
        color="blue", fill=True, fill_opacity=0.5,
        popup=f"<b>{info['name']}</b><br>Ngày thường: {pred_wd:.0f} lượt"
    ).add_to(fg_weekday)

    # Marker cuối tuần
    folium.CircleMarker(
        [info["lat"] + 0.002, info["lon"] + 0.002],
        radius=max(8, pred_we / 4),
        color="red", fill=True, fill_opacity=0.5,
        popup=f"<b>{info['name']}</b><br>Cuối tuần: {pred_we:.0f} lượt"
    ).add_to(fg_weekend)

    # Label chênh lệch
    folium.Marker(
        [info["lat"], info["lon"]],
        icon=folium.DivIcon(html=f"""
            <div style="font-size:11px; font-weight:bold; color:#333;
                 background:white; padding:2px 6px; border-radius:4px;
                 border:1px solid #ccc; white-space:nowrap">
                {info['name']}<br>
                <span style="color:{'green' if diff > 0 else 'red'}">
                    {arrow} {abs(diff_pct):.0f}%
                </span>
            </div>
        """)
    ).add_to(m2)

fg_weekday.add_to(m2)
fg_weekend.add_to(m2)
folium.LayerControl().add_to(m2)

title2 = """
<div style="position:fixed; top:10px; left:50%; transform:translateX(-50%);
     z-index:9999; background:white; padding:10px 20px; border-radius:8px;
     box-shadow:0 2px 6px rgba(0,0,0,0.3); font-family:Arial">
    <h3 style="margin:0; color:#333">So sánh nhu cầu: Ngày thường vs Cuối tuần</h3>
    <p style="margin:4px 0 0; color:#666; font-size:12px">
        🟦 Ngày thường &nbsp; 🟥 Cuối tuần &nbsp;|&nbsp;
#         % = mức thay đổi cuối tuần so với ngày thường
    </p>
</div>
"""
m2.get_root().html.add_child(folium.Element(title2))
m2.save("bai_23_11_map2_compare.html")
print("✅ Đã lưu bản đồ 2: bai_23_11_map2_compare.html")

# --- BẢN ĐỒ 3: Heatmap nhu cầu theo các khung giờ ---
m3 = folium.Map(location=[10.79, 106.70], zoom_start=13,
                tiles='CartoDB positron')

time_slots = {
    "Sáng sớm (7h)": 7,
    "Trưa (12h)": 12,
    "Chiều cao điểm (18h)": 18,
    "Tối khuya (22h)": 22
}

for slot_name, hour in time_slots.items():
    fg = folium.FeatureGroup(name=slot_name)
    heat_data = []

    for region_id, info in regions.items():
        pred = model.predict(pd.DataFrame([{
            "region_id": region_id, "hour": hour,
            "day_of_week": 3, "is_weekend": 0
        }]))[0]

        # Tạo nhiều điểm xung quanh trung tâm khu vực để tạo heatmap đẹp
        for _ in range(int(pred)):
            lat = info["lat"] + np.random.normal(0, 0.004)
            lon = info["lon"] + np.random.normal(0, 0.004)
            heat_data.append([lat, lon, 1])

    HeatMap(heat_data, radius=15, blur=10, max_zoom=15).add_to(fg)
    fg.add_to(m3)

folium.LayerControl(collapsed=False).add_to(m3)

title3 = """
<div style="position:fixed; top:10px; left:50%; transform:translateX(-50%);
     z-index:9999; background:white; padding:10px 20px; border-radius:8px;
     box-shadow:0 2px 6px rgba(0,0,0,0.3); font-family:Arial">
    <h3 style="margin:0">Heatmap nhu cầu gọi xe theo khung giờ</h3>
    <p style="margin:4px 0 0; color:#666; font-size:12px">
        Bật/tắt từng khung giờ ở bảng điều khiển bên phải
    </p>
</div>
"""
m3.get_root().html.add_child(folium.Element(title3))
m3.save("bai_23_11_map3_heatmap.html")
print("✅ Đã lưu bản đồ 3: bai_23_11_map3_heatmap.html")

# ==============================================================
# 4. PHÂN TÍCH VÀ NHẬN XÉT
# ==============================================================
print(f"""
{'='*60}
📊 PHÂN TÍCH SỰ KHÁC BIỆT NHU CẦU GIỮA CÁC KHU VỰC
{'='*60}

1. KHU VỰC NHU CẦU CAO:
   - Quận 1: Trung tâm thương mại, văn phòng → nhu cầu cao cả ngày
   - Quận 3: Khu vực dân cư + thương mại mật độ cao
   → Cần bố trí NHIỀU tài xế nhất ở 2 khu vực này

2. SỰ KHÁC BIỆT NGÀY THƯỜNG vs CUỐI TUẦN:
   - Quận 1, Quận 7: Nhu cầu TĂNG cuối tuần (giải trí, mua sắm)
   - Thủ Đức, Gò Vấp: Nhu cầu GIẢM cuối tuần (ít đi làm)
   → Cần điều chuyển tài xế từ ngoại thành vào trung tâm cuối tuần

3. KHUNG GIỜ CAO ĐIỂM:
   - 7h-9h sáng: Nhu cầu cao ở khu dân cư (đi làm)
   - 17h-19h chiều: Nhu cầu cao nhất trong ngày (tan làm + giải trí)
   - 22h+: Nhu cầu giảm mạnh → có thể giảm số xe hoạt động

4. Ý NGHĨA TRONG ĐIỀU PHỐI NGUỒN LỰC:
   - Dùng mô hình dự đoán để phân bổ tài xế TRƯỚC giờ cao điểm
   - Áp dụng giá surge (giá động) ở khu vực nhu cầu > cung
   - Khuyến khích tài xế di chuyển đến vùng sắp có nhu cầu cao
   - Tiết kiệm chi phí bằng cách giảm xe ở giờ/vùng nhu cầu thấp
""")

# Mở bản đồ chính trong trình duyệt
webbrowser.open('file://' + os.path.realpath("bai_23_11_map1_weekday.html"))
m

#23.12
import numpy as np
import folium
from geopy.distance import geodesic
import webbrowser, os

np.random.seed(42)

# 1. Dữ liệu: 2 kho + 16 điểm giao hàng ở TP.HCM
warehouses = [
    {"name": "Kho Q1",  "lat": 10.7756, "lon": 106.7019},
    {"name": "Kho Q7",  "lat": 10.7340, "lon": 106.7215},
]
delivery_points = []
for i in range(16):
    delivery_points.append({
        "name": f"Đơn {i+1}",
        "lat": 10.74 + np.random.uniform(-0.04, 0.06),
        "lon": 106.67 + np.random.uniform(-0.02, 0.06),
    })

def dist(a, b):
    return geodesic((a["lat"], a["lon"]), (b["lat"], b["lon"])).km

# 2. Gán mỗi điểm cho kho gần nhất
for p in delivery_points:
    dists = [dist(p, w) for w in warehouses]
    p["warehouse"] = int(np.argmin(dists))

# 3. Nearest Neighbor heuristic (tối ưu)
def nearest_neighbor(warehouse, points):
    route = [warehouse]
    remaining = points.copy()
    current = warehouse
    total = 0
    while remaining:
        nearest = min(remaining, key=lambda p: dist(current, p))
        total += dist(current, nearest)
        route.append(nearest)
        remaining.remove(nearest)
        current = nearest
    total += dist(current, warehouse)  # quay về kho
    route.append(warehouse)
    return route, round(total, 2)

# 4. Phương án không tối ưu (theo thứ tự nhận đơn)
def naive_route(warehouse, points):
    route = [warehouse] + points + [warehouse]
    total = sum(dist(route[i], route[i+1]) for i in range(len(route)-1))
    return route, round(total, 2)

# 5. Tính tuyến đường cho mỗi kho
colors = ["blue", "red"]
m = folium.Map(location=[10.76, 106.70], zoom_start=14, tiles="CartoDB positron")

total_opt, total_naive = 0, 0
for w_idx, w in enumerate(warehouses):
    pts = [p for p in delivery_points if p["warehouse"] == w_idx]

    route_opt, dist_opt = nearest_neighbor(w, pts)
    route_naive, dist_naive = naive_route(w, pts)
    saving = ((dist_naive - dist_opt) / dist_naive) * 100

    total_opt += dist_opt
    total_naive += dist_naive

    # Vẽ tuyến tối ưu
    folium.PolyLine(
        [[p["lat"], p["lon"]] for p in route_opt],
        color=colors[w_idx], weight=4, opacity=0.8,
        tooltip=f"{w['name']} — Tối ưu: {dist_opt} km (tiết kiệm {saving:.0f}%)"
    ).add_to(m)

    # Vẽ tuyến naive (mờ hơn)
    folium.PolyLine(
        [[p["lat"], p["lon"]] for p in route_naive],
        color=colors[w_idx], weight=2, opacity=0.3, dash_array="8",
        tooltip=f"{w['name']} — Không tối ưu: {dist_naive} km"
    ).add_to(m)

    # Marker kho
    folium.Marker([w["lat"], w["lon"]], tooltip=w["name"],
                  icon=folium.Icon(color=colors[w_idx], icon="home")).add_to(m)

    # Marker điểm giao
    for i, p in enumerate(pts):
        folium.CircleMarker(
            [p["lat"], p["lon"]], radius=6,
            color=colors[w_idx], fill=True, fill_opacity=0.8,
            tooltip=f"{p['name']} (→ {w['name']})"
        ).add_to(m)

    print(f"{w['name']}: {len(pts)} điểm | Tối ưu: {dist_opt}km | Naive: {dist_naive}km | Tiết kiệm: {saving:.1f}%")

# Chú thích
saving_total = ((total_naive - total_opt) / total_naive) * 100
legend = f"""
<div style="position:fixed;bottom:30px;left:30px;z-index:9999;background:white;
     padding:12px;border-radius:8px;box-shadow:0 2px 6px rgba(0,0,0,0.3);font-size:12px">
    <b>Bài 23.12 — Tối ưu tuyến giao hàng</b><br>
    🔵 Kho Q1 &nbsp; 🔴 Kho Q7<br>
    ── Tuyến tối ưu (Nearest Neighbor) &nbsp; - - Tuyến không tối ưu<br>
    <b>Tổng tiết kiệm: {saving_total:.1f}% quãng đường</b>
</div>"""
m.get_root().html.add_child(folium.Element(legend))
m.save("bai_23_12.html")
webbrowser.open('file://' + os.path.realpath("bai_23_12.html"))

print(f"\nTỔNG: Tối ưu {total_opt:.1f}km vs Naive {total_naive:.1f}km → Tiết kiệm {saving_total:.1f}%")
m

#23.13
import numpy as np
import folium
from folium.plugins import HeatMap, MiniMap, Fullscreen
import webbrowser, os

np.random.seed(42)
center = [10.78, 106.70]

m = folium.Map(location=center, zoom_start=13, tiles="CartoDB positron")
folium.TileLayer("OpenStreetMap", name="OpenStreetMap").add_to(m)

# === LỚP 1: ĐIỂM — Kho hàng ===
fg_warehouses = folium.FeatureGroup(name="🏭 Kho hàng")
wh_list = [
    {"name": "Kho Trung tâm", "lat": 10.775, "lon": 106.700, "cap": 500},
    {"name": "Kho Bắc",       "lat": 10.810, "lon": 106.680, "cap": 300},
    {"name": "Kho Nam",        "lat": 10.740, "lon": 106.720, "cap": 350},
]
for w in wh_list:
    folium.Marker(
        [w["lat"], w["lon"]], tooltip=f"{w['name']} ({w['cap']} đơn/ngày)",
        popup=f"<b>{w['name']}</b><br>Công suất: {w['cap']} đơn/ngày",
        icon=folium.Icon(color="red", icon="home")
    ).add_to(fg_warehouses)
fg_warehouses.add_to(m)

# === LỚP 2: VÙNG — Service area (bán kính phục vụ) ===
fg_zones = folium.FeatureGroup(name="🔵 Vùng phục vụ (3km, 5km)")
for w in wh_list:
    folium.Circle([w["lat"], w["lon"]], radius=3000,
                  color="blue", fill=True, fill_opacity=0.05,
                  tooltip=f"{w['name']} — 3km").add_to(fg_zones)
    folium.Circle([w["lat"], w["lon"]], radius=5000,
                  color="navy", fill=True, fill_opacity=0.03,
                  dash_array="5", tooltip=f"{w['name']} — 5km").add_to(fg_zones)
fg_zones.add_to(m)

# === LỚP 3: ĐIỂM — Khách hàng ===
fg_customers = folium.FeatureGroup(name="👤 Khách hàng (80 điểm)")
customers = np.vstack([
    np.random.normal([10.775, 106.700], 0.008, (30, 2)),
    np.random.normal([10.810, 106.680], 0.006, (25, 2)),
    np.random.normal([10.740, 106.720], 0.006, (25, 2)),
])
for i, c in enumerate(customers):
    folium.CircleMarker(
        c.tolist(), radius=3, color="orange", fill=True, fill_opacity=0.7,
        tooltip=f"Khách {i+1}"
    ).add_to(fg_customers)
fg_customers.add_to(m)

# === LỚP 4: HEATMAP — Mật độ khách hàng ===
fg_heat = folium.FeatureGroup(name="🌡️ Heatmap mật độ khách")
HeatMap(customers.tolist(), radius=18, blur=12).add_to(fg_heat)
fg_heat.add_to(m)

# === LỚP 5: TUYẾN ĐƯỜNG — Giao hàng mẫu ===
fg_routes = folium.FeatureGroup(name="🚚 Tuyến giao hàng")
colors = ["blue", "green", "purple"]
for idx, w in enumerate(wh_list):
    # Lấy 5 khách gần kho nhất
    from geopy.distance import geodesic
    dists = [(geodesic((w["lat"], w["lon"]), (c[0], c[1])).km, i) for i, c in enumerate(customers)]
    dists.sort()
    nearest_5 = [customers[i] for _, i in dists[:5]]
    route = [[w["lat"], w["lon"]]] + [c.tolist() for c in nearest_5] + [[w["lat"], w["lon"]]]
    folium.PolyLine(route, color=colors[idx], weight=3, opacity=0.7,
                    tooltip=f"Tuyến từ {w['name']}").add_to(fg_routes)
fg_routes.add_to(m)

# === LỚP 6: VÙNG CẢNH BÁO — Khu vực chưa phục vụ tốt ===
fg_alert = folium.FeatureGroup(name="⚠️ Vùng cần mở rộng")
folium.Circle([10.82, 106.74], radius=2000, color="red",
              fill=True, fill_opacity=0.1,
              tooltip="Vùng chưa có kho — cần mở rộng").add_to(fg_alert)
fg_alert.add_to(m)

# Plugins
MiniMap(toggle_display=True).add_to(m)
Fullscreen().add_to(m)
folium.LayerControl(collapsed=False).add_to(m)

# Tiêu đề
title = """
<div style="position:fixed;top:10px;left:50%;transform:translateX(-50%);z-index:9999;
     background:white;padding:10px 20px;border-radius:8px;box-shadow:0 2px 6px rgba(0,0,0,0.3);
     font-family:Arial;font-size:13px">
    <b>Dashboard quản trị Logistics TP.HCM</b> — 6 lớp dữ liệu | Bật/tắt bên phải
</div>"""
m.get_root().html.add_child(folium.Element(title))
m.save("bai_23_13.html")
webbrowser.open('file://' + os.path.realpath("bai_23_13.html"))
print("✅ Dashboard gồm: Kho, Vùng phục vụ, Khách hàng, Heatmap, Tuyến giao hàng, Vùng cảnh báo")
m

#23.14
import numpy as np
import folium
from folium.plugins import TimestampedGeoJson
import webbrowser, os, json
from datetime import datetime, timedelta

np.random.seed(42)

# 1. Định nghĩa mạng đường đơn giản (các nút giao TP.HCM)
nodes = {
    "A": (10.780, 106.700),  # Ngã tư Nguyễn Huệ
    "B": (10.785, 106.695),  # Ngã tư CMT8
    "C": (10.790, 106.700),  # Ngã tư Điện Biên Phủ
    "D": (10.785, 106.705),  # Hai Bà Trưng
    "E": (10.775, 106.695),  # Nguyễn Thị Minh Khai
    "F": (10.770, 106.700),  # Trần Hưng Đạo
    "G": (10.775, 106.705),  # Pasteur
    "H": (10.790, 106.690),  # Lý Thường Kiệt
}

# 2. Định nghĩa 4 xe với lộ trình khác nhau
vehicles = [
    {"id": "Xe 1", "color": "#e74c3c", "route": ["A", "B", "H", "C", "D", "A"]},
    {"id": "Xe 2", "color": "#3498db", "route": ["F", "E", "B", "C", "D", "G", "F"]},
    {"id": "Xe 3", "color": "#2ecc71", "route": ["C", "H", "B", "E", "F", "G", "D", "C"]},
    {"id": "Xe 4", "color": "#9b59b6", "route": ["G", "D", "C", "B", "A", "E", "F", "G"]},
]

# 3. Tạo dữ liệu di chuyển với nội suy (mượt hơn)
base_time = datetime(2024, 1, 1, 8, 0, 0)

def interpolate(p1, p2, steps=5):
    """Nội suy giữa 2 điểm để xe di chuyển mượt"""
    lats = np.linspace(p1[0], p2[0], steps + 1)[:-1]
    lons = np.linspace(p1[1], p2[1], steps + 1)[:-1]
    return list(zip(lats, lons))

features = []
for v in vehicles:
    coords = []
    times = []
    t = base_time
    for i in range(len(v["route"]) - 1):
        p1 = nodes[v["route"][i]]
        p2 = nodes[v["route"][i + 1]]
        interp = interpolate(p1, p2, steps=6)
        for pt in interp:
            coords.append([pt[1], pt[0]])  # GeoJSON: [lon, lat]
            times.append(t.strftime("%Y-%m-%dT%H:%M:%S"))
            t += timedelta(minutes=2)
    # Điểm cuối
    last = nodes[v["route"][-1]]
    coords.append([last[1], last[0]])
    times.append(t.strftime("%Y-%m-%dT%H:%M:%S"))

    features.append({
        "type": "Feature",
        "geometry": {"type": "LineString", "coordinates": coords},
        "properties": {
            "times": times,
            "style": {"color": v["color"], "weight": 5},
            "icon": "circle",
            "iconstyle": {
                "fillColor": v["color"], "fillOpacity": 0.9,
                "stroke": "true", "radius": 7
            },
            "popup": f"<b>{v['id']}</b><br>Lộ trình: {' → '.join(v['route'])}",
            "tooltip": v["id"]
        }
    })

# 4. Vẽ bản đồ
m = folium.Map(location=[10.782, 106.699], zoom_start=16, tiles="CartoDB positron")

# Vẽ mạng đường nền
edges = [("A","B"),("B","C"),("B","H"),("C","D"),("D","G"),("D","A"),
         ("A","E"),("E","B"),("E","F"),("F","G"),("G","A")]
for n1, n2 in edges:
    folium.PolyLine([nodes[n1], nodes[n2]], color="gray",
                    weight=2, opacity=0.4).add_to(m)

# Marker các nút giao
for name, coord in nodes.items():
    folium.CircleMarker(coord, radius=5, color="#333", fill=True,
                        fill_opacity=0.6, tooltip=f"Nút {name}").add_to(m)

# Animation xe di chuyển
TimestampedGeoJson(
    {"type": "FeatureCollection", "features": features},
    period="PT2M",        # mỗi bước = 2 phút
    duration="PT1M",      # vết xe hiển thị 1 phút
    auto_play=True,
    loop=True,
    max_speed=5,
    add_last_point=True,
).add_to(m)

legend = """
<div style="position:fixed;bottom:30px;left:30px;z-index:9999;background:white;
     padding:12px;border-radius:8px;box-shadow:0 2px 6px rgba(0,0,0,0.3);font-size:12px">
    <b>Bài 23.14 — Mô phỏng điều phối xe</b><br>
    🔴 Xe 1 &nbsp; 🔵 Xe 2 &nbsp; 🟢 Xe 3 &nbsp; 🟣 Xe 4<br>
    Nhấn ▶ để xem xe di chuyển theo thời gian
</div>"""
m.get_root().html.add_child(folium.Element(legend))
m.save("bai_23_14.html")
webbrowser.open('file://' + os.path.realpath("bai_23_14.html"))

print("✅ Mở bản đồ → nhấn nút Play ▶ để xem 4 xe di chuyển trên mạng đường theo thời gian")
for v in vehicles:
    print(f"  {v['id']}: {' → '.join(v['route'])}")
m

#23.15
import numpy as np
import folium
from folium.plugins import HeatMap
from sklearn.cluster import KMeans
from geopy.distance import geodesic
import webbrowser, os

np.random.seed(42)

# ============================================================
# 1. BÀI TOÁN
# ============================================================
# Một doanh nghiệp muốn mở 3 quán cà phê mới tại TP.HCM.
# Cần tìm vị trí tối ưu dựa trên: mật độ dân cư, mức độ cạnh tranh,
# khả năng tiếp cận giao thông. Dùng AI để chấm điểm + gợi ý vị trí.

# ============================================================
# 2. DỮ LIỆU (giả lập)
# ============================================================

# 2a. Mật độ dân cư — 300 điểm dân cư
pop_clusters = [
    (10.780, 106.700, 80),   # Q1 - trung tâm
    (10.800, 106.680, 60),   # Q3
    (10.735, 106.720, 50),   # Q7
    (10.850, 106.760, 40),   # Thủ Đức
    (10.760, 106.670, 35),   # Q5
    (10.810, 106.650, 35),   # Tân Bình
]
population = np.vstack([
    np.random.normal([lat, lon], 0.006, (n, 2)) for lat, lon, n in pop_clusters
])

# 2b. Quán cà phê đối thủ hiện có — 20 quán
competitors = [
    {"name": "Highlands Q1",    "lat": 10.776, "lon": 106.701},
    {"name": "Starbucks Nguyễn Huệ", "lat": 10.774, "lon": 106.703},
    {"name": "Phúc Long Lê Lợi","lat": 10.772, "lon": 106.698},
    {"name": "TCH Pasteur",     "lat": 10.785, "lon": 106.697},
    {"name": "Highlands Q3",    "lat": 10.790, "lon": 106.685},
    {"name": "Starbucks Q3",    "lat": 10.795, "lon": 106.680},
    {"name": "Phúc Long Q7",    "lat": 10.738, "lon": 106.722},
    {"name": "TCH Q7",          "lat": 10.730, "lon": 106.718},
    {"name": "Highlands Q5",    "lat": 10.755, "lon": 106.665},
    {"name": "Phúc Long Q5",    "lat": 10.758, "lon": 106.672},
    {"name": "TCH Thủ Đức",     "lat": 10.848, "lon": 106.758},
    {"name": "Highlands TB",    "lat": 10.808, "lon": 106.652},
    {"name": "Starbucks BT",    "lat": 10.805, "lon": 106.710},
    {"name": "Coffee House NTL","lat": 10.792, "lon": 106.695},
    {"name": "Phúc Long ĐBP",   "lat": 10.787, "lon": 106.692},
    {"name": "Highlands GV",    "lat": 10.838, "lon": 106.665},
    {"name": "Ông Bầu Q10",    "lat": 10.775, "lon": 106.675},
    {"name": "Trung Nguyên Q1", "lat": 10.778, "lon": 106.695},
    {"name": "Cộng Cà Phê",    "lat": 10.780, "lon": 106.705},
    {"name": "Katinat ND Chiểu","lat": 10.793, "lon": 106.700},
]

# 2c. Trạm xe buýt / metro (tiếp cận giao thông)
transit = [
    (10.773, 106.700), (10.780, 106.692), (10.788, 106.697),
    (10.795, 106.685), (10.758, 106.670), (10.735, 106.720),
    (10.848, 106.755), (10.810, 106.650), (10.770, 106.705),
    (10.803, 106.710),
]

# ============================================================
# 3. PHƯƠNG PHÁP AI — Scoring Model
# ============================================================

# Tạo lưới ứng viên (grid) trên toàn TP.HCM
lat_range = np.arange(10.720, 10.860, 0.005)
lon_range = np.arange(10.640, 106.770, 0.005)
# Sửa lại lon_range
lon_range = np.arange(106.640, 106.770, 0.005)

candidates = []
for lat in lat_range:
    for lon in lon_range:
        # Score 1: Mật độ dân cư (đếm số dân trong bán kính 500m)
        pop_count = sum(1 for p in population
                        if geodesic((lat, lon), (p[0], p[1])).m < 500)
        pop_score = min(pop_count / 15, 1.0)  # chuẩn hóa 0-1

        # Score 2: Cạnh tranh (ít đối thủ gần = tốt)
        comp_nearby = sum(1 for c in competitors
                          if geodesic((lat, lon), (c["lat"], c["lon"])).m < 400)
        comp_score = max(0, 1 - comp_nearby / 3)  # 0 đối thủ=1, ≥3=0

        # Score 3: Gần giao thông công cộng
        min_transit = min(geodesic((lat, lon), t).m for t in transit)
        transit_score = max(0, 1 - min_transit / 800)  # <800m = tốt

        # Tổng điểm (trọng số: dân cư 50%, cạnh tranh 30%, giao thông 20%)
        total = pop_score * 0.5 + comp_score * 0.3 + transit_score * 0.2

        if total > 0.2:  # chỉ giữ điểm đáng xem xét
            candidates.append({
                "lat": lat, "lon": lon,
                "pop_score": round(pop_score, 2),
                "comp_score": round(comp_score, 2),
                "transit_score": round(transit_score, 2),
                "total": round(total, 3)
            })

# Sắp xếp theo điểm
candidates.sort(key=lambda x: -x["total"])
print(f"Tổng ứng viên đánh giá: {len(candidates)}")

# ============================================================
# 4. AI — KMeans chọn 3 vị trí tối ưu (phân tán, không chồng nhau)
# ============================================================
top_n = min(30, len(candidates))
top_candidates = candidates[:top_n]
top_coords = np.array([[c["lat"], c["lon"]] for c in top_candidates])

kmeans = KMeans(n_clusters=3, random_state=42).fit(top_coords)
# Chọn ứng viên điểm cao nhất trong mỗi cluster
best_3 = []
for cluster_id in range(3):
    cluster_cands = [c for c, l in zip(top_candidates, kmeans.labels_) if l == cluster_id]
    best = max(cluster_cands, key=lambda x: x["total"])
    best_3.append(best)

# ============================================================
# 5. TRỰC QUAN HÓA TRÊN BẢN ĐỒ
# ============================================================
m = folium.Map(location=[10.785, 106.700], zoom_start=13, tiles="CartoDB positron")

# Lớp 1: Heatmap dân cư
fg_pop = folium.FeatureGroup(name="🌡️ Mật độ dân cư")
HeatMap(population.tolist(), radius=12, blur=8).add_to(fg_pop)
fg_pop.add_to(m)

# Lớp 2: Đối thủ
fg_comp = folium.FeatureGroup(name="☕ Đối thủ hiện có")
for c in competitors:
    folium.CircleMarker(
        [c["lat"], c["lon"]], radius=5, color="gray", fill=True, fill_opacity=0.7,
        tooltip=c["name"]
    ).add_to(fg_comp)
fg_comp.add_to(m)

# Lớp 3: Giao thông
fg_transit = folium.FeatureGroup(name="🚌 Trạm giao thông")
for t in transit:
    folium.CircleMarker(t, radius=4, color="blue", fill=True,
                        fill_opacity=0.5, tooltip="Trạm xe buýt/metro").add_to(fg_transit)
fg_transit.add_to(m)

# Lớp 4: 3 vị trí đề xuất
fg_result = folium.FeatureGroup(name="⭐ VỊ TRÍ ĐỀ XUẤT")
colors = ["red", "green", "purple"]
for i, loc in enumerate(best_3):
    folium.Marker(
        [loc["lat"], loc["lon"]],
        icon=folium.Icon(color=colors[i], icon="star"),
        tooltip=f"ĐỀ XUẤT #{i+1} — Điểm: {loc['total']:.2f}",
        popup=f"<b>Vị trí đề xuất #{i+1}</b><br>"
              f"Dân cư: {loc['pop_score']:.0%}<br>"
              f"Cạnh tranh: {loc['comp_score']:.0%}<br>"
              f"Giao thông: {loc['transit_score']:.0%}<br>"
              f"<b>TỔNG: {loc['total']:.0%}</b>"
    ).add_to(fg_result)
    folium.Circle([loc["lat"], loc["lon"]], radius=500,
                  color=colors[i], fill=True, fill_opacity=0.1).add_to(fg_result)
fg_result.add_to(m)

folium.LayerControl(collapsed=False).add_to(m)

legend = """
<div style="position:fixed;bottom:30px;left:30px;z-index:9999;background:white;
     padding:12px;border-radius:8px;box-shadow:0 2px 6px rgba(0,0,0,0.3);font-size:12px">
    <b>Bài 23.15 — AI đề xuất vị trí mở quán cà phê</b><br>
    ⭐ Vị trí đề xuất &nbsp; ☕ Đối thủ &nbsp; 🚌 Giao thông &nbsp; 🌡️ Dân cư<br>
    Scoring: Dân cư 50% + Ít cạnh tranh 30% + Giao thông 20%
</div>"""
m.get_root().html.add_child(folium.Element(legend))
m.save("bai_23_15.html")
webbrowser.open('file://' + os.path.realpath("bai_23_15.html"))

# ============================================================
# 6. BÁO CÁO KẾT QUẢ
# ============================================================
print(f"""
{'='*55}
📋 BÁO CÁO: ĐỀ XUẤT VỊ TRÍ MỞ QUÁN CÀ PHÊ TẠI TP.HCM
{'='*55}

1. BÀI TOÁN:
   Tìm 3 vị trí tối ưu mở quán cà phê dựa trên dữ liệu không gian.

2. DỮ LIỆU:
   - 300 điểm dân cư (giả lập theo phân bố thực tế 6 quận)
   - 20 quán cà phê đối thủ (Highlands, Starbucks, Phúc Long...)
   - 10 trạm giao thông công cộng

3. PHƯƠNG PHÁP AI:
   a) Scoring Model: Lưới 728 ứng viên, chấm điểm 3 tiêu chí
      - Mật độ dân cư trong 500m (trọng số 50%)
      - Mức độ cạnh tranh trong 400m (trọng số 30%)
      - Khoảng cách đến giao thông (trọng số 20%)
   b) KMeans (K=3): Phân cụm top 30 ứng viên → chọn tốt nhất
      mỗi cụm → đảm bảo 3 vị trí phân tán, không cannibalize.

4. KẾT QUẢ:""")
for i, loc in enumerate(best_3):
    print(f"   ⭐ Vị trí #{i+1}: ({loc['lat']:.3f}, {loc['lon']:.3f})")
    print(f"      Dân cư={loc['pop_score']:.0%}  Cạnh tranh={loc['comp_score']:.0%}  "
          f"Giao thông={loc['transit_score']:.0%}  TỔNG={loc['total']:.0%}")

print(f"""
5. GIÁ TRỊ ỨNG DỤNG:
   - Giảm rủi ro chọn sai vị trí (nguyên nhân #1 thất bại F&B).
   - Tái sử dụng cho chuỗi bất kỳ: trà sữa, minimart, gym...
   - Mở rộng: tích hợp dữ liệu giá thuê, lưu lượng người đi bộ,
     doanh thu khu vực → mô hình chính xác hơn.
""")
m

